### ISSUE TITLE
ZSH support

### ISSUE THREAD

**Issue by dkvdm** [project-rootbox/rootbox#2]
Right now rootbox requires Bash 4.3 or higher. Can you elaborate why this is?
Any chance on supporting ZSH? Thanks!

**Comment by refi64** [comment]
Although there aren't really any plans for this, I think you might misunderstand why Rootbox requires Bash.

Rootbox is entirely written in Bash scripts. Therefore, supporting zsh would require basically an entire rewrite. IIRC there was some Bash features I used that required 4.3 over any 4.x, but I forgot what it was (I *really* should've put a comment!).

That being said, Rootbox doesn't require your actual *shell* to be bash. So, if you have bash installed, you can use Rootbox, even if your main shell is zsh!
